# Generated by Django 4.1.1 on 2022-10-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_athlete_scout'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height_ft',
            field=models.IntegerField(choices=[(4, '4'), (5, '5'), (6, '6'), (7, '7')], default=5),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height_in',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=6),
        ),
        migrations.AddField(
            model_name='athlete',
            name='school',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight_lb',
            field=models.IntegerField(default=140),
        ),
    ]
