# Generated by Django 4.1.1 on 2022-11-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='height_ft',
            field=models.IntegerField(blank=True, choices=[(4, '4'), (5, '5'), (6, '6'), (7, '7')], default=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height_in',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=6),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight_lb',
            field=models.IntegerField(blank=True, default=140),
        ),
    ]
