# Generated by Django 4.1.1 on 2022-11-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
